name: keyboard
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-174.2.beta

# Add regular dependencies here.
dependencies:
  dart_tolk: ^1.4.0
  ffi: ^2.1.0
  recase: ^4.1.0
  win32: ^5.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
